/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GithubConnectRouteImport } from './routes/github-connect'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ProjectProjectIdRouteRouteImport } from './routes/project/$projectId/route'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdPullsRouteImport } from './routes/project/$projectId/pulls'
import { Route as ApiProjectsFromGithubRouteImport } from './routes/api/projects/from-github'
import { Route as ApiMobileAuthRouteImport } from './routes/api/mobile/auth'
import { Route as ApiGrokStatusRouteImport } from './routes/api/grok/status'
import { Route as ApiGrokDisconnectRouteImport } from './routes/api/grok/disconnect'
import { Route as ApiGithubRepositoriesRouteImport } from './routes/api/github/repositories'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiCodexStatusRouteImport } from './routes/api/codex/status'
import { Route as ApiCodexDisconnectRouteImport } from './routes/api/codex/disconnect'
import { Route as ApiChatgptLwcRouteImport } from './routes/api/chatgpt/$lwc'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ProjectProjectIdThreadRouteRouteImport } from './routes/project/$projectId/thread/route'
import { Route as ProjectProjectIdThreadThreadIdRouteImport } from './routes/project/$projectId/thread/$threadId'
import { Route as ApiWorkosWidgetsPipesTokenRouteImport } from './routes/api/workos/widgets/pipes-token'
import { Route as ApiProjectProjectIdPullsRouteImport } from './routes/api/project/$projectId/pulls'
import { Route as ApiProjectProjectIdBranchRouteImport } from './routes/api/project/$projectId/branch'
import { Route as ApiGrokDeviceStartRouteImport } from './routes/api/grok/device/start'
import { Route as ApiGrokDevicePollRouteImport } from './routes/api/grok/device/poll'
import { Route as ApiCodexDeviceStartRouteImport } from './routes/api/codex/device/start'
import { Route as ApiCodexDevicePollRouteImport } from './routes/api/codex/device/poll'
import { Route as ApiAgentIdStreamRouteImport } from './routes/api/agent/$id/stream'
import { Route as ApiProjectProjectIdThreadThreadIdRouteImport } from './routes/api/project/$projectId/thread/$threadId'
import { Route as ApiProjectProjectIdThreadThreadIdPullRequestRouteImport } from './routes/api/project/$projectId/thread/$threadId/pull-request'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent'
import { Route as ApiGithubRepositoriesOwnerRepoBranchesRouteImport } from './routes/api/github/repositories/$owner/$repo/branches'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent/$runId'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent/$runId/stream'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubConnectRoute = GithubConnectRouteImport.update({
  id: '/github-connect',
  path: '/github-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRouteRoute = ProjectProjectIdRouteRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const ProjectProjectIdPullsRoute = ProjectProjectIdPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const ApiProjectsFromGithubRoute = ApiProjectsFromGithubRouteImport.update({
  id: '/api/projects/from-github',
  path: '/api/projects/from-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileAuthRoute = ApiMobileAuthRouteImport.update({
  id: '/api/mobile/auth',
  path: '/api/mobile/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokStatusRoute = ApiGrokStatusRouteImport.update({
  id: '/api/grok/status',
  path: '/api/grok/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokDisconnectRoute = ApiGrokDisconnectRouteImport.update({
  id: '/api/grok/disconnect',
  path: '/api/grok/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRepositoriesRoute = ApiGithubRepositoriesRouteImport.update({
  id: '/api/github/repositories',
  path: '/api/github/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexStatusRoute = ApiCodexStatusRouteImport.update({
  id: '/api/codex/status',
  path: '/api/codex/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexDisconnectRoute = ApiCodexDisconnectRouteImport.update({
  id: '/api/codex/disconnect',
  path: '/api/codex/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatgptLwcRoute = ApiChatgptLwcRouteImport.update({
  id: '/api/chatgpt/$lwc',
  path: '/api/chatgpt/$lwc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdThreadRouteRoute =
  ProjectProjectIdThreadRouteRouteImport.update({
    id: '/thread',
    path: '/thread',
    getParentRoute: () => ProjectProjectIdRouteRoute,
  } as any)
const ProjectProjectIdThreadThreadIdRoute =
  ProjectProjectIdThreadThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ProjectProjectIdThreadRouteRoute,
  } as any)
const ApiWorkosWidgetsPipesTokenRoute =
  ApiWorkosWidgetsPipesTokenRouteImport.update({
    id: '/api/workos/widgets/pipes-token',
    path: '/api/workos/widgets/pipes-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectProjectIdPullsRoute =
  ApiProjectProjectIdPullsRouteImport.update({
    id: '/api/project/$projectId/pulls',
    path: '/api/project/$projectId/pulls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectProjectIdBranchRoute =
  ApiProjectProjectIdBranchRouteImport.update({
    id: '/api/project/$projectId/branch',
    path: '/api/project/$projectId/branch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGrokDeviceStartRoute = ApiGrokDeviceStartRouteImport.update({
  id: '/api/grok/device/start',
  path: '/api/grok/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokDevicePollRoute = ApiGrokDevicePollRouteImport.update({
  id: '/api/grok/device/poll',
  path: '/api/grok/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexDeviceStartRoute = ApiCodexDeviceStartRouteImport.update({
  id: '/api/codex/device/start',
  path: '/api/codex/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexDevicePollRoute = ApiCodexDevicePollRouteImport.update({
  id: '/api/codex/device/poll',
  path: '/api/codex/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentIdStreamRoute = ApiAgentIdStreamRouteImport.update({
  id: '/$id/stream',
  path: '/$id/stream',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiProjectProjectIdThreadThreadIdRoute =
  ApiProjectProjectIdThreadThreadIdRouteImport.update({
    id: '/api/project/$projectId/thread/$threadId',
    path: '/api/project/$projectId/thread/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectProjectIdThreadThreadIdPullRequestRoute =
  ApiProjectProjectIdThreadThreadIdPullRequestRouteImport.update({
    id: '/pull-request',
    path: '/pull-request',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRoute =
  ApiProjectProjectIdThreadThreadIdAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdRoute,
  } as any)
const ApiGithubRepositoriesOwnerRepoBranchesRoute =
  ApiGithubRepositoriesOwnerRepoBranchesRouteImport.update({
    id: '/$owner/$repo/branches',
    path: '/$owner/$repo/branches',
    getParentRoute: () => ApiGithubRepositoriesRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRunIdRoute =
  ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdAgentRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute =
  ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdAgentRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/github-connect': typeof GithubConnectRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/chatgpt/$lwc': typeof ApiChatgptLwcRoute
  '/api/codex/disconnect': typeof ApiCodexDisconnectRoute
  '/api/codex/status': typeof ApiCodexStatusRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/grok/disconnect': typeof ApiGrokDisconnectRoute
  '/api/grok/status': typeof ApiGrokStatusRoute
  '/api/mobile/auth': typeof ApiMobileAuthRoute
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/codex/device/poll': typeof ApiCodexDevicePollRoute
  '/api/codex/device/start': typeof ApiCodexDeviceStartRoute
  '/api/grok/device/poll': typeof ApiGrokDevicePollRoute
  '/api/grok/device/start': typeof ApiGrokDeviceStartRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/api/workos/widgets/pipes-token': typeof ApiWorkosWidgetsPipesTokenRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/github-connect': typeof GithubConnectRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/chatgpt/$lwc': typeof ApiChatgptLwcRoute
  '/api/codex/disconnect': typeof ApiCodexDisconnectRoute
  '/api/codex/status': typeof ApiCodexStatusRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/grok/disconnect': typeof ApiGrokDisconnectRoute
  '/api/grok/status': typeof ApiGrokStatusRoute
  '/api/mobile/auth': typeof ApiMobileAuthRoute
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/codex/device/poll': typeof ApiCodexDevicePollRoute
  '/api/codex/device/start': typeof ApiCodexDeviceStartRoute
  '/api/grok/device/poll': typeof ApiGrokDevicePollRoute
  '/api/grok/device/start': typeof ApiGrokDeviceStartRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/api/workos/widgets/pipes-token': typeof ApiWorkosWidgetsPipesTokenRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/github-connect': typeof GithubConnectRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/settings/$section': typeof SettingsSectionRoute
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/chatgpt/$lwc': typeof ApiChatgptLwcRoute
  '/api/codex/disconnect': typeof ApiCodexDisconnectRoute
  '/api/codex/status': typeof ApiCodexStatusRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/grok/disconnect': typeof ApiGrokDisconnectRoute
  '/api/grok/status': typeof ApiGrokStatusRoute
  '/api/mobile/auth': typeof ApiMobileAuthRoute
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/codex/device/poll': typeof ApiCodexDevicePollRoute
  '/api/codex/device/start': typeof ApiCodexDeviceStartRoute
  '/api/grok/device/poll': typeof ApiGrokDevicePollRoute
  '/api/grok/device/start': typeof ApiGrokDeviceStartRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/api/workos/widgets/pipes-token': typeof ApiWorkosWidgetsPipesTokenRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/github-connect'
    | '/settings'
    | '/sign-up'
    | '/project/$projectId'
    | '/api/agent'
    | '/settings/$section'
    | '/project/$projectId/thread'
    | '/api/auth/sign-in'
    | '/api/chatgpt/$lwc'
    | '/api/codex/disconnect'
    | '/api/codex/status'
    | '/api/github/connect'
    | '/api/github/repositories'
    | '/api/grok/disconnect'
    | '/api/grok/status'
    | '/api/mobile/auth'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId/'
    | '/api/agent/$id/stream'
    | '/api/codex/device/poll'
    | '/api/codex/device/start'
    | '/api/grok/device/poll'
    | '/api/grok/device/start'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/api/workos/widgets/pipes-token'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/github-connect'
    | '/settings'
    | '/sign-up'
    | '/api/agent'
    | '/settings/$section'
    | '/project/$projectId/thread'
    | '/api/auth/sign-in'
    | '/api/chatgpt/$lwc'
    | '/api/codex/disconnect'
    | '/api/codex/status'
    | '/api/github/connect'
    | '/api/github/repositories'
    | '/api/grok/disconnect'
    | '/api/grok/status'
    | '/api/mobile/auth'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId'
    | '/api/agent/$id/stream'
    | '/api/codex/device/poll'
    | '/api/codex/device/start'
    | '/api/grok/device/poll'
    | '/api/grok/device/start'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/api/workos/widgets/pipes-token'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/dashboard'
    | '/github-connect'
    | '/settings'
    | '/sign-up'
    | '/project/$projectId'
    | '/api/agent'
    | '/settings/$section'
    | '/project/$projectId/thread'
    | '/api/auth/sign-in'
    | '/api/chatgpt/$lwc'
    | '/api/codex/disconnect'
    | '/api/codex/status'
    | '/api/github/connect'
    | '/api/github/repositories'
    | '/api/grok/disconnect'
    | '/api/grok/status'
    | '/api/mobile/auth'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId/'
    | '/api/agent/$id/stream'
    | '/api/codex/device/poll'
    | '/api/codex/device/start'
    | '/api/grok/device/poll'
    | '/api/grok/device/start'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/api/workos/widgets/pipes-token'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  GithubConnectRoute: typeof GithubConnectRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  ProjectProjectIdRouteRoute: typeof ProjectProjectIdRouteRouteWithChildren
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiChatgptLwcRoute: typeof ApiChatgptLwcRoute
  ApiCodexDisconnectRoute: typeof ApiCodexDisconnectRoute
  ApiCodexStatusRoute: typeof ApiCodexStatusRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubRepositoriesRoute: typeof ApiGithubRepositoriesRouteWithChildren
  ApiGrokDisconnectRoute: typeof ApiGrokDisconnectRoute
  ApiGrokStatusRoute: typeof ApiGrokStatusRoute
  ApiMobileAuthRoute: typeof ApiMobileAuthRoute
  ApiProjectsFromGithubRoute: typeof ApiProjectsFromGithubRoute
  ApiCodexDevicePollRoute: typeof ApiCodexDevicePollRoute
  ApiCodexDeviceStartRoute: typeof ApiCodexDeviceStartRoute
  ApiGrokDevicePollRoute: typeof ApiGrokDevicePollRoute
  ApiGrokDeviceStartRoute: typeof ApiGrokDeviceStartRoute
  ApiProjectProjectIdBranchRoute: typeof ApiProjectProjectIdBranchRoute
  ApiProjectProjectIdPullsRoute: typeof ApiProjectProjectIdPullsRoute
  ApiWorkosWidgetsPipesTokenRoute: typeof ApiWorkosWidgetsPipesTokenRoute
  ApiProjectProjectIdThreadThreadIdRoute: typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-connect': {
      id: '/github-connect'
      path: '/github-connect'
      fullPath: '/github-connect'
      preLoaderRoute: typeof GithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/project/$projectId/pulls': {
      id: '/project/$projectId/pulls'
      path: '/pulls'
      fullPath: '/project/$projectId/pulls'
      preLoaderRoute: typeof ProjectProjectIdPullsRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/api/projects/from-github': {
      id: '/api/projects/from-github'
      path: '/api/projects/from-github'
      fullPath: '/api/projects/from-github'
      preLoaderRoute: typeof ApiProjectsFromGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/auth': {
      id: '/api/mobile/auth'
      path: '/api/mobile/auth'
      fullPath: '/api/mobile/auth'
      preLoaderRoute: typeof ApiMobileAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok/status': {
      id: '/api/grok/status'
      path: '/api/grok/status'
      fullPath: '/api/grok/status'
      preLoaderRoute: typeof ApiGrokStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok/disconnect': {
      id: '/api/grok/disconnect'
      path: '/api/grok/disconnect'
      fullPath: '/api/grok/disconnect'
      preLoaderRoute: typeof ApiGrokDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repositories': {
      id: '/api/github/repositories'
      path: '/api/github/repositories'
      fullPath: '/api/github/repositories'
      preLoaderRoute: typeof ApiGithubRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/status': {
      id: '/api/codex/status'
      path: '/api/codex/status'
      fullPath: '/api/codex/status'
      preLoaderRoute: typeof ApiCodexStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/disconnect': {
      id: '/api/codex/disconnect'
      path: '/api/codex/disconnect'
      fullPath: '/api/codex/disconnect'
      preLoaderRoute: typeof ApiCodexDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatgpt/$lwc': {
      id: '/api/chatgpt/$lwc'
      path: '/api/chatgpt/$lwc'
      fullPath: '/api/chatgpt/$lwc'
      preLoaderRoute: typeof ApiChatgptLwcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/thread': {
      id: '/project/$projectId/thread'
      path: '/thread'
      fullPath: '/project/$projectId/thread'
      preLoaderRoute: typeof ProjectProjectIdThreadRouteRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/project/$projectId/thread/$threadId': {
      id: '/project/$projectId/thread/$threadId'
      path: '/$threadId'
      fullPath: '/project/$projectId/thread/$threadId'
      preLoaderRoute: typeof ProjectProjectIdThreadThreadIdRouteImport
      parentRoute: typeof ProjectProjectIdThreadRouteRoute
    }
    '/api/workos/widgets/pipes-token': {
      id: '/api/workos/widgets/pipes-token'
      path: '/api/workos/widgets/pipes-token'
      fullPath: '/api/workos/widgets/pipes-token'
      preLoaderRoute: typeof ApiWorkosWidgetsPipesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$projectId/pulls': {
      id: '/api/project/$projectId/pulls'
      path: '/api/project/$projectId/pulls'
      fullPath: '/api/project/$projectId/pulls'
      preLoaderRoute: typeof ApiProjectProjectIdPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$projectId/branch': {
      id: '/api/project/$projectId/branch'
      path: '/api/project/$projectId/branch'
      fullPath: '/api/project/$projectId/branch'
      preLoaderRoute: typeof ApiProjectProjectIdBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok/device/start': {
      id: '/api/grok/device/start'
      path: '/api/grok/device/start'
      fullPath: '/api/grok/device/start'
      preLoaderRoute: typeof ApiGrokDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok/device/poll': {
      id: '/api/grok/device/poll'
      path: '/api/grok/device/poll'
      fullPath: '/api/grok/device/poll'
      preLoaderRoute: typeof ApiGrokDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/device/start': {
      id: '/api/codex/device/start'
      path: '/api/codex/device/start'
      fullPath: '/api/codex/device/start'
      preLoaderRoute: typeof ApiCodexDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/device/poll': {
      id: '/api/codex/device/poll'
      path: '/api/codex/device/poll'
      fullPath: '/api/codex/device/poll'
      preLoaderRoute: typeof ApiCodexDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$id/stream': {
      id: '/api/agent/$id/stream'
      path: '/$id/stream'
      fullPath: '/api/agent/$id/stream'
      preLoaderRoute: typeof ApiAgentIdStreamRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/project/$projectId/thread/$threadId': {
      id: '/api/project/$projectId/thread/$threadId'
      path: '/api/project/$projectId/thread/$threadId'
      fullPath: '/api/project/$projectId/thread/$threadId'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$projectId/thread/$threadId/pull-request': {
      id: '/api/project/$projectId/thread/$threadId/pull-request'
      path: '/pull-request'
      fullPath: '/api/project/$projectId/thread/$threadId/pull-request'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdPullRequestRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdRoute
    }
    '/api/project/$projectId/thread/$threadId/agent': {
      id: '/api/project/$projectId/thread/$threadId/agent'
      path: '/agent'
      fullPath: '/api/project/$projectId/thread/$threadId/agent'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdRoute
    }
    '/api/github/repositories/$owner/$repo/branches': {
      id: '/api/github/repositories/$owner/$repo/branches'
      path: '/$owner/$repo/branches'
      fullPath: '/api/github/repositories/$owner/$repo/branches'
      preLoaderRoute: typeof ApiGithubRepositoriesOwnerRepoBranchesRouteImport
      parentRoute: typeof ApiGithubRepositoriesRoute
    }
    '/api/project/$projectId/thread/$threadId/agent/$runId': {
      id: '/api/project/$projectId/thread/$threadId/agent/$runId'
      path: '/$runId'
      fullPath: '/api/project/$projectId/thread/$threadId/agent/$runId'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRoute
    }
    '/api/project/$projectId/thread/$threadId/agent/$runId/stream': {
      id: '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
      path: '/stream'
      fullPath: '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectProjectIdThreadRouteRouteChildren {
  ProjectProjectIdThreadThreadIdRoute: typeof ProjectProjectIdThreadThreadIdRoute
}

const ProjectProjectIdThreadRouteRouteChildren: ProjectProjectIdThreadRouteRouteChildren =
  {
    ProjectProjectIdThreadThreadIdRoute: ProjectProjectIdThreadThreadIdRoute,
  }

const ProjectProjectIdThreadRouteRouteWithChildren =
  ProjectProjectIdThreadRouteRoute._addFileChildren(
    ProjectProjectIdThreadRouteRouteChildren,
  )

interface ProjectProjectIdRouteRouteChildren {
  ProjectProjectIdThreadRouteRoute: typeof ProjectProjectIdThreadRouteRouteWithChildren
  ProjectProjectIdPullsRoute: typeof ProjectProjectIdPullsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteRouteChildren: ProjectProjectIdRouteRouteChildren = {
  ProjectProjectIdThreadRouteRoute:
    ProjectProjectIdThreadRouteRouteWithChildren,
  ProjectProjectIdPullsRoute: ProjectProjectIdPullsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteRouteWithChildren =
  ProjectProjectIdRouteRoute._addFileChildren(
    ProjectProjectIdRouteRouteChildren,
  )

interface ApiAgentRouteChildren {
  ApiAgentIdStreamRoute: typeof ApiAgentIdStreamRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentIdStreamRoute: ApiAgentIdStreamRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

interface ApiGithubRepositoriesRouteChildren {
  ApiGithubRepositoriesOwnerRepoBranchesRoute: typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
}

const ApiGithubRepositoriesRouteChildren: ApiGithubRepositoriesRouteChildren = {
  ApiGithubRepositoriesOwnerRepoBranchesRoute:
    ApiGithubRepositoriesOwnerRepoBranchesRoute,
}

const ApiGithubRepositoriesRouteWithChildren =
  ApiGithubRepositoriesRoute._addFileChildren(
    ApiGithubRepositoriesRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}

const ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren: ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute:
      ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute,
  }

const ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdAgentRunIdRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdAgentRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRunIdRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
}

const ApiProjectProjectIdThreadThreadIdAgentRouteChildren: ApiProjectProjectIdThreadThreadIdAgentRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRunIdRoute:
      ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren,
  }

const ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdAgentRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdAgentRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  ApiProjectProjectIdThreadThreadIdPullRequestRoute: typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
}

const ApiProjectProjectIdThreadThreadIdRouteChildren: ApiProjectProjectIdThreadThreadIdRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRoute:
      ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren,
    ApiProjectProjectIdThreadThreadIdPullRequestRoute:
      ApiProjectProjectIdThreadThreadIdPullRequestRoute,
  }

const ApiProjectProjectIdThreadThreadIdRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  GithubConnectRoute: GithubConnectRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignUpRoute: SignUpRoute,
  ProjectProjectIdRouteRoute: ProjectProjectIdRouteRouteWithChildren,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiChatgptLwcRoute: ApiChatgptLwcRoute,
  ApiCodexDisconnectRoute: ApiCodexDisconnectRoute,
  ApiCodexStatusRoute: ApiCodexStatusRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubRepositoriesRoute: ApiGithubRepositoriesRouteWithChildren,
  ApiGrokDisconnectRoute: ApiGrokDisconnectRoute,
  ApiGrokStatusRoute: ApiGrokStatusRoute,
  ApiMobileAuthRoute: ApiMobileAuthRoute,
  ApiProjectsFromGithubRoute: ApiProjectsFromGithubRoute,
  ApiCodexDevicePollRoute: ApiCodexDevicePollRoute,
  ApiCodexDeviceStartRoute: ApiCodexDeviceStartRoute,
  ApiGrokDevicePollRoute: ApiGrokDevicePollRoute,
  ApiGrokDeviceStartRoute: ApiGrokDeviceStartRoute,
  ApiProjectProjectIdBranchRoute: ApiProjectProjectIdBranchRoute,
  ApiProjectProjectIdPullsRoute: ApiProjectProjectIdPullsRoute,
  ApiWorkosWidgetsPipesTokenRoute: ApiWorkosWidgetsPipesTokenRoute,
  ApiProjectProjectIdThreadThreadIdRoute:
    ApiProjectProjectIdThreadThreadIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
