/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ProjectProjectIdRouteRouteImport } from './routes/project/$projectId/route'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdPullsRouteImport } from './routes/project/$projectId/pulls'
import { Route as ApiProjectsFromGithubRouteImport } from './routes/api/projects/from-github'
import { Route as ApiGithubRepositoriesRouteImport } from './routes/api/github/repositories'
import { Route as ProjectProjectIdThreadRouteRouteImport } from './routes/project/$projectId/thread/route'
import { Route as ProjectProjectIdThreadThreadIdRouteImport } from './routes/project/$projectId/thread/$threadId'
import { Route as ApiProjectProjectIdPullsRouteImport } from './routes/api/project/$projectId/pulls'
import { Route as ApiProjectProjectIdBranchRouteImport } from './routes/api/project/$projectId/branch'
import { Route as ApiAgentIdStreamRouteImport } from './routes/api/agent/$id/stream'
import { Route as ApiProjectProjectIdThreadThreadIdRouteImport } from './routes/api/project/$projectId/thread/$threadId'
import { Route as ApiProjectProjectIdThreadThreadIdPullRequestRouteImport } from './routes/api/project/$projectId/thread/$threadId/pull-request'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent'
import { Route as ApiGithubRepositoriesOwnerRepoBranchesRouteImport } from './routes/api/github/repositories/$owner/$repo/branches'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent/$runId'
import { Route as ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport } from './routes/api/project/$projectId/thread/$threadId/agent/$runId/stream'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRouteRoute = ProjectProjectIdRouteRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const ProjectProjectIdPullsRoute = ProjectProjectIdPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const ApiProjectsFromGithubRoute = ApiProjectsFromGithubRouteImport.update({
  id: '/api/projects/from-github',
  path: '/api/projects/from-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRepositoriesRoute = ApiGithubRepositoriesRouteImport.update({
  id: '/api/github/repositories',
  path: '/api/github/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdThreadRouteRoute =
  ProjectProjectIdThreadRouteRouteImport.update({
    id: '/thread',
    path: '/thread',
    getParentRoute: () => ProjectProjectIdRouteRoute,
  } as any)
const ProjectProjectIdThreadThreadIdRoute =
  ProjectProjectIdThreadThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ProjectProjectIdThreadRouteRoute,
  } as any)
const ApiProjectProjectIdPullsRoute =
  ApiProjectProjectIdPullsRouteImport.update({
    id: '/api/project/$projectId/pulls',
    path: '/api/project/$projectId/pulls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectProjectIdBranchRoute =
  ApiProjectProjectIdBranchRouteImport.update({
    id: '/api/project/$projectId/branch',
    path: '/api/project/$projectId/branch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentIdStreamRoute = ApiAgentIdStreamRouteImport.update({
  id: '/$id/stream',
  path: '/$id/stream',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiProjectProjectIdThreadThreadIdRoute =
  ApiProjectProjectIdThreadThreadIdRouteImport.update({
    id: '/api/project/$projectId/thread/$threadId',
    path: '/api/project/$projectId/thread/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectProjectIdThreadThreadIdPullRequestRoute =
  ApiProjectProjectIdThreadThreadIdPullRequestRouteImport.update({
    id: '/pull-request',
    path: '/pull-request',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRoute =
  ApiProjectProjectIdThreadThreadIdAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdRoute,
  } as any)
const ApiGithubRepositoriesOwnerRepoBranchesRoute =
  ApiGithubRepositoriesOwnerRepoBranchesRouteImport.update({
    id: '/$owner/$repo/branches',
    path: '/$owner/$repo/branches',
    getParentRoute: () => ApiGithubRepositoriesRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRunIdRoute =
  ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdAgentRoute,
  } as any)
const ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute =
  ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport.update({
    id: '/stream',
    path: '/stream',
    getParentRoute: () => ApiProjectProjectIdThreadThreadIdAgentRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/project/$projectId/thread': typeof ProjectProjectIdThreadRouteRouteWithChildren
  '/api/github/repositories': typeof ApiGithubRepositoriesRouteWithChildren
  '/api/projects/from-github': typeof ApiProjectsFromGithubRoute
  '/project/$projectId/pulls': typeof ProjectProjectIdPullsRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/agent/$id/stream': typeof ApiAgentIdStreamRoute
  '/api/project/$projectId/branch': typeof ApiProjectProjectIdBranchRoute
  '/api/project/$projectId/pulls': typeof ApiProjectProjectIdPullsRoute
  '/project/$projectId/thread/$threadId': typeof ProjectProjectIdThreadThreadIdRoute
  '/api/project/$projectId/thread/$threadId': typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
  '/api/github/repositories/$owner/$repo/branches': typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
  '/api/project/$projectId/thread/$threadId/agent': typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  '/api/project/$projectId/thread/$threadId/pull-request': typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
  '/api/project/$projectId/thread/$threadId/agent/$runId': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
  '/api/project/$projectId/thread/$threadId/agent/$runId/stream': typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/project/$projectId'
    | '/api/agent'
    | '/project/$projectId/thread'
    | '/api/github/repositories'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId/'
    | '/api/agent/$id/stream'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/agent'
    | '/project/$projectId/thread'
    | '/api/github/repositories'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId'
    | '/api/agent/$id/stream'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/project/$projectId'
    | '/api/agent'
    | '/project/$projectId/thread'
    | '/api/github/repositories'
    | '/api/projects/from-github'
    | '/project/$projectId/pulls'
    | '/project/$projectId/'
    | '/api/agent/$id/stream'
    | '/api/project/$projectId/branch'
    | '/api/project/$projectId/pulls'
    | '/project/$projectId/thread/$threadId'
    | '/api/project/$projectId/thread/$threadId'
    | '/api/github/repositories/$owner/$repo/branches'
    | '/api/project/$projectId/thread/$threadId/agent'
    | '/api/project/$projectId/thread/$threadId/pull-request'
    | '/api/project/$projectId/thread/$threadId/agent/$runId'
    | '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProjectProjectIdRouteRoute: typeof ProjectProjectIdRouteRouteWithChildren
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiGithubRepositoriesRoute: typeof ApiGithubRepositoriesRouteWithChildren
  ApiProjectsFromGithubRoute: typeof ApiProjectsFromGithubRoute
  ApiProjectProjectIdBranchRoute: typeof ApiProjectProjectIdBranchRoute
  ApiProjectProjectIdPullsRoute: typeof ApiProjectProjectIdPullsRoute
  ApiProjectProjectIdThreadThreadIdRoute: typeof ApiProjectProjectIdThreadThreadIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/project/$projectId/pulls': {
      id: '/project/$projectId/pulls'
      path: '/pulls'
      fullPath: '/project/$projectId/pulls'
      preLoaderRoute: typeof ProjectProjectIdPullsRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/api/projects/from-github': {
      id: '/api/projects/from-github'
      path: '/api/projects/from-github'
      fullPath: '/api/projects/from-github'
      preLoaderRoute: typeof ApiProjectsFromGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repositories': {
      id: '/api/github/repositories'
      path: '/api/github/repositories'
      fullPath: '/api/github/repositories'
      preLoaderRoute: typeof ApiGithubRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/thread': {
      id: '/project/$projectId/thread'
      path: '/thread'
      fullPath: '/project/$projectId/thread'
      preLoaderRoute: typeof ProjectProjectIdThreadRouteRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/project/$projectId/thread/$threadId': {
      id: '/project/$projectId/thread/$threadId'
      path: '/$threadId'
      fullPath: '/project/$projectId/thread/$threadId'
      preLoaderRoute: typeof ProjectProjectIdThreadThreadIdRouteImport
      parentRoute: typeof ProjectProjectIdThreadRouteRoute
    }
    '/api/project/$projectId/pulls': {
      id: '/api/project/$projectId/pulls'
      path: '/api/project/$projectId/pulls'
      fullPath: '/api/project/$projectId/pulls'
      preLoaderRoute: typeof ApiProjectProjectIdPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$projectId/branch': {
      id: '/api/project/$projectId/branch'
      path: '/api/project/$projectId/branch'
      fullPath: '/api/project/$projectId/branch'
      preLoaderRoute: typeof ApiProjectProjectIdBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$id/stream': {
      id: '/api/agent/$id/stream'
      path: '/$id/stream'
      fullPath: '/api/agent/$id/stream'
      preLoaderRoute: typeof ApiAgentIdStreamRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/project/$projectId/thread/$threadId': {
      id: '/api/project/$projectId/thread/$threadId'
      path: '/api/project/$projectId/thread/$threadId'
      fullPath: '/api/project/$projectId/thread/$threadId'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project/$projectId/thread/$threadId/pull-request': {
      id: '/api/project/$projectId/thread/$threadId/pull-request'
      path: '/pull-request'
      fullPath: '/api/project/$projectId/thread/$threadId/pull-request'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdPullRequestRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdRoute
    }
    '/api/project/$projectId/thread/$threadId/agent': {
      id: '/api/project/$projectId/thread/$threadId/agent'
      path: '/agent'
      fullPath: '/api/project/$projectId/thread/$threadId/agent'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdRoute
    }
    '/api/github/repositories/$owner/$repo/branches': {
      id: '/api/github/repositories/$owner/$repo/branches'
      path: '/$owner/$repo/branches'
      fullPath: '/api/github/repositories/$owner/$repo/branches'
      preLoaderRoute: typeof ApiGithubRepositoriesOwnerRepoBranchesRouteImport
      parentRoute: typeof ApiGithubRepositoriesRoute
    }
    '/api/project/$projectId/thread/$threadId/agent/$runId': {
      id: '/api/project/$projectId/thread/$threadId/agent/$runId'
      path: '/$runId'
      fullPath: '/api/project/$projectId/thread/$threadId/agent/$runId'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRoute
    }
    '/api/project/$projectId/thread/$threadId/agent/$runId/stream': {
      id: '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
      path: '/stream'
      fullPath: '/api/project/$projectId/thread/$threadId/agent/$runId/stream'
      preLoaderRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRouteImport
      parentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRoute
    }
  }
}

interface ProjectProjectIdThreadRouteRouteChildren {
  ProjectProjectIdThreadThreadIdRoute: typeof ProjectProjectIdThreadThreadIdRoute
}

const ProjectProjectIdThreadRouteRouteChildren: ProjectProjectIdThreadRouteRouteChildren =
  {
    ProjectProjectIdThreadThreadIdRoute: ProjectProjectIdThreadThreadIdRoute,
  }

const ProjectProjectIdThreadRouteRouteWithChildren =
  ProjectProjectIdThreadRouteRoute._addFileChildren(
    ProjectProjectIdThreadRouteRouteChildren,
  )

interface ProjectProjectIdRouteRouteChildren {
  ProjectProjectIdThreadRouteRoute: typeof ProjectProjectIdThreadRouteRouteWithChildren
  ProjectProjectIdPullsRoute: typeof ProjectProjectIdPullsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteRouteChildren: ProjectProjectIdRouteRouteChildren = {
  ProjectProjectIdThreadRouteRoute:
    ProjectProjectIdThreadRouteRouteWithChildren,
  ProjectProjectIdPullsRoute: ProjectProjectIdPullsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteRouteWithChildren =
  ProjectProjectIdRouteRoute._addFileChildren(
    ProjectProjectIdRouteRouteChildren,
  )

interface ApiAgentRouteChildren {
  ApiAgentIdStreamRoute: typeof ApiAgentIdStreamRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentIdStreamRoute: ApiAgentIdStreamRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

interface ApiGithubRepositoriesRouteChildren {
  ApiGithubRepositoriesOwnerRepoBranchesRoute: typeof ApiGithubRepositoriesOwnerRepoBranchesRoute
}

const ApiGithubRepositoriesRouteChildren: ApiGithubRepositoriesRouteChildren = {
  ApiGithubRepositoriesOwnerRepoBranchesRoute:
    ApiGithubRepositoriesOwnerRepoBranchesRoute,
}

const ApiGithubRepositoriesRouteWithChildren =
  ApiGithubRepositoriesRoute._addFileChildren(
    ApiGithubRepositoriesRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute
}

const ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren: ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute:
      ApiProjectProjectIdThreadThreadIdAgentRunIdStreamRoute,
  }

const ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdAgentRunIdRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdAgentRunIdRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdAgentRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRunIdRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren
}

const ApiProjectProjectIdThreadThreadIdAgentRouteChildren: ApiProjectProjectIdThreadThreadIdAgentRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRunIdRoute:
      ApiProjectProjectIdThreadThreadIdAgentRunIdRouteWithChildren,
  }

const ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdAgentRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdAgentRouteChildren,
  )

interface ApiProjectProjectIdThreadThreadIdRouteChildren {
  ApiProjectProjectIdThreadThreadIdAgentRoute: typeof ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren
  ApiProjectProjectIdThreadThreadIdPullRequestRoute: typeof ApiProjectProjectIdThreadThreadIdPullRequestRoute
}

const ApiProjectProjectIdThreadThreadIdRouteChildren: ApiProjectProjectIdThreadThreadIdRouteChildren =
  {
    ApiProjectProjectIdThreadThreadIdAgentRoute:
      ApiProjectProjectIdThreadThreadIdAgentRouteWithChildren,
    ApiProjectProjectIdThreadThreadIdPullRequestRoute:
      ApiProjectProjectIdThreadThreadIdPullRequestRoute,
  }

const ApiProjectProjectIdThreadThreadIdRouteWithChildren =
  ApiProjectProjectIdThreadThreadIdRoute._addFileChildren(
    ApiProjectProjectIdThreadThreadIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProjectProjectIdRouteRoute: ProjectProjectIdRouteRouteWithChildren,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiGithubRepositoriesRoute: ApiGithubRepositoriesRouteWithChildren,
  ApiProjectsFromGithubRoute: ApiProjectsFromGithubRoute,
  ApiProjectProjectIdBranchRoute: ApiProjectProjectIdBranchRoute,
  ApiProjectProjectIdPullsRoute: ApiProjectProjectIdPullsRoute,
  ApiProjectProjectIdThreadThreadIdRoute:
    ApiProjectProjectIdThreadThreadIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
